export const AchievementActionTypes = {
  ADD_ACHIEVEMENT: 'ADD_ACHIEVEMENT',
  DELETE_ACHIEVEMENT: 'DELETE_ACHIEVEMENT',
  UPDATE_ACHIEVEMENT_TITLE: 'UPDATE_ACHIEVEMENT_TITLE',
  UPDATE_SELECTED_A: 'UPDATE_SELECTED_A',
  UPDATE_SELECTED_B: 'UPDATE_SELECTED_B',
  GET_ACHIEVEMENTS: 'GET_ACHIEVEMENTS'
}